### PR TITLE
pull request: animated weather icons

### PR DESCRIPTION
**Pull request by LoveBootCaptain**
and here we are again. animated weather icons in 8x8 px.

sadly i was not able to draw a good raspberry or a pimoroni pirate yet.
need some time to test some things but i don't have the old unicorn-hat set up.
i hope the code runs like on unicorn-hat-hd... but it should, i guess ;)

kind regards again from berlin

stephan

### CODE REVIEW

**Comment by LoveBootCaptain** [comment]
Is there any problem with the PR? Wondering because it is not merged yet.
Just tell me if I have to change something.
Kind regards from Berlin

**Comment by Gadgetoid** [comment]
No problem (at least not that I'm aware of!). I just haven't had a chance to test and merge it yet.

**Comment by Gadgetoid** [comment]
Merged, thank you! I moved it into the `hat` folder for examples, since it wont work on the pHAT, and also tidied up the README slightly. Otherwise, great effort squeezing them all into 8x8!

**Comment by LoveBootCaptain** [comment]
Hey Philip,

great... I just thought there might be a problem. thx for cleaning it up so
that it fits into the main project.
next week i will have some free days and i will make them even more perfect.

i also build a complete weather station with unicorn-hat, scroll-hat and
blinkt on a black-hat. nearly no soldering required.
might the be interesting too as an example? if yes i would put some more
effort in it to make it work for everyone.
check my repos, it is called UnicornWeather (
https://github.com/LoveBootCaptain/UnicornWeather).

it is a little messy at the moment, but hey... it works.

kind regards from berlin and thx for the merge

stephan

2017-07-18 16:24 GMT+02:00 Philip Howard <notifications@github.com>:

**Pull request merged**
