### PR TITLE
Create Toggle.py

### PR DESCRIPTION
**Pull request by Pyroseza**
This is the first commit to Toggle.py

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Any reason why it's pHAT only? You should be able to get the width/height of the detected device and set either 4x8 or 8x8 pixels.

```
width, height = unicorn.get_shape()
```

**Comment by Pyroseza** [comment]
Hi,

I don't have an 8x8 Hat to test it on, so I thought it would be safer to
just release for 4x8 pHat and someone else could test and confirm for me.

I'll make the change you've suggested and test on the 4x8 phat

Thank you!

Kind Regards,
Jarrod Price

**Comment by Gadgetoid** [comment]
Thank you! Oh, one more thing- can you rename to `toggle.py`

We're ever the pedants :D

**Comment by Pyroseza** [comment]
Sure thing, what would you like me to call it?

On_off_with_input.py ?

Kind Regards,
Jarrod Price

--------

**Comment by RogueM** [comment]
I think @Gadgetoid just meant to use the uncapitalised `toggle.py`

**Comment by Pyroseza** [comment]
Oh whoops I misread, sure will do that 

Kind Regards,
Jarrod Price

--------

**Comment by Pyroseza** [comment]
Closing this request, moving file to parent directory and will create a new pull request

**Pull request closed without merging**
